creating our work section (work in progress)
codeJunctionTeam/codeJunction-site pull request #40
Opened 2020-04-18 20:51 UTC by rajitha1998

Fixes #20 

## Proposed Changes

  - Creating project cards 
  - Setting the number of cards based on screen size
  - Switch card functionality 

## Screenshots

2020-04-25 17:59 UTC, rajitha1998 commented
Build failing because of this [issue in is-promise](https://github.com/then/is-promise/issues/13)  😞@janethavi @hasalfernando @nandulaperera @Purushothh

2020-04-25 18:09 UTC, hasalfernando commented
@rajitha1998 seems the issue isn't resolved yet. Let's wait for it to be resolved. However, the issue you mentioned isn't the active one. It is currently closed. [This](https://github.com/then/is-promise/issues/20) is the active issue thread.

2020-05-09 16:43 UTC, nandulaperera approved these changes
Nice work @rajitha1998

2020-05-09 16:43 UTC, janethavi commented on src/app/components/our-work/our-work.component.html
> +</div>
Shall we add an EOF line here?

2020-05-09 16:43 UTC, janethavi commented on src/app/components/project-card/project-card.component.html
> +</div>
Shall we add an EOF line here?

2020-05-09 16:44 UTC, janethavi commented on src/assets/json/projects.json
> +]
Shall we add an EOF line here?

2020-05-09 16:45 UTC, janethavi commented on src/app/components/components.component.html
> +</div>
Shall we add an EOF line here?

2020-05-09 16:49 UTC, janethavi commented on src/app/components/our-work/our-work.component.html
> +                        class="	fa fa-angle-left"></i></button>
Shall we remove the extra space in the CSS class value?

2020-05-09 17:11 UTC, hasalfernando reviewed
Nice work @rajitha1998 

I found some things that needs to be adjusted in the project cards.

### Cake-a-licious Website card
Change the name Codejunction to "codeJunction".

### Ajith motors Entry System card
Change "according to the type of account(staff/admin)" to "according to the type of account (staff/admin)".

### Fhix45 card
Remove the first sentence "This is one of the projects which was undertaken from codeJunction".

### CodeJunction Website card
Change the name "CodeJunction" to "codeJunction" in both the title and the description.


Shall we update these changes?

2020-05-09 18:39 UTC, janethavi requested changes

2020-05-09 18:39 UTC, janethavi commented on src/app/components/components.component.ts
> +
Shall we remove this extra line?

2020-05-09 18:39 UTC, janethavi commented on src/app/components/our-work/our-work.component.html
> +</div>
Shall we add the EOF line here?

2020-05-09 18:39 UTC, janethavi commented on src/assets/json/projects.json
> +]
Shall we add the EOF line here?

2020-05-09 18:55 UTC, janethavi commented
Great work @rajitha1998! Nicely done🚀

2020-05-09 18:56 UTC, janethavi approved these changes

2020-05-09 18:57 UTC, hasalfernando approved these changes
Well done @rajitha1998 Nice work!

2020-05-09 18:58 UTC, merged